### ISSUE TITLE
spring cloud：eureka

### ISSUE THREAD

**Issue by sunyanhui123** [sunyanhui123/note#132]
### 简单开启注册中心、注册服务
1、在启动类增加注解@EnableEurekaServer将该服务作为注册中心server
2、注册中心常用配置
```
server:
  port: 8761 #指定端口

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #禁止将自己注册到注册中心
    fetchRegistry: false #是否需要去注册中心获取其他服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
```

3、开启一个服务提供者：在启动类增加注册@EnableEurekaClient
4、服务提供者配置文件：
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #指定注册中心地址
server:
  port: 8762
spring:
  application:
    name: service-hi #指定服务名
```
### 注册中心高可用
开启多台server，然后将自己也注册到注册中心。
1、激活属性registerWithEureka和fetchRegistry。将自己注册到注册中心，同时从注册中心拉取服务。
2、将url地址指向注册中心其他server
```
server:
  port: 8761 #指定端口

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #禁止将自己注册到注册中心
    fetchRegistry: false #是否需要去注册中心获取其他服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #指向注册中心其他server地址
```
3、服务提供者将注册中心地址改成多个server
```
eureka:
  client:
    serviceUrl:
      defaultZone: server1,server2 #指定注册所有server
server:
  port: 8762
spring:
  application:
    name: service-hi #指定服务名
```
